const CATEGORIES_ACTION_TYPES = {
    SET_CATEGORIES: 'categories/SET_CATEGORIES',
    FETCH_CATEGORY_START: 'categories/FETCH_CATEGORY_START',
    FETCH_CATEGORY_SUCCESS: 'categories/FETCH_CATEGORY_SUCCESS',
    FETCH_CATEGORY_FAILURE: 'categories/FETCH_CATEGORY_FAILURE',
};

export default CATEGORIES_ACTION_TYPES;